# DIML dataset training configuration

# General settings
save-dir: ./experiments
logstep-train: 10
save-model: both
val-every-n-epochs: 1
seed: 12345

# Dataset settings
dataset: DIML               # Using DIML dataset
data-dir: ./datafolder      # Path to DIML dataset directory
num-workers: 8
batch-size: 8
crop-size: 256
scaling: 8
max-rotation: 15.0
in-memory: false

# Training settings
loss: l1
num-epochs: 1000
lr: 0.0001
w-decay: 1e-5
lr-scheduler: step
lr-step: 100
lr-gamma: 0.9
gradient-clip: 0.01

# Model settings
feature-extractor: UNet
Npre: 8000
Ntrain: 1024

# Transformer options
use-transformer: true
transformer-blocks: 2
transformer-heads: 8 